language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"

# command to install dependencies
install: pip install $DJANGO

# command to run tests
script: script/test-command
